//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PII_2022_II_P1_2021220030
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DetallesFactura = new ObservableCollection<DetallesFactura>();
        }
    
        public int FacturaID { get; set; }
        public int EmpleadoID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal SubTotal { get; set; }
        public decimal ISV { get; set; }
        public decimal Descuento { get; set; }
        public decimal TotalPagar { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DetallesFactura> DetallesFactura { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
